.TH "FUSEISO" "1" "October 2005" "" ""
.SH NAME
\fBfuseiso\fP \- mounts isofs images with FUSE
.SH SYNOPSIS
\fBfuseiso\fP <isofs_image_file> <mountpoint> [<FUSE library options>]
.br
.SH DESCRIPTION
This manual page documents briefly the
.B fuseiso
command.
.PP
\fBfuseiso\fP mounts isofs images using FUSE technology.
.PP
This manual page was written by Kel Modderman <kelrin@tpg.com.au>,
for the Debian project (but may be used by others).
